swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Roll damping prediction
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /roll_damping:
    get:
      operationId: roll_damping.predict
      tags:
        - roll_damping
      summary: Predict the roll damping of a ship, based on its main dimensions.
      description: Make prediction for *one* ship.
      parameters:
        - name: lpp
          in: query
          description: Ship perpendicular length [m]
          type: number
          required: True

        - name: beam
          in: query
          description: Ship beam [m]
          type: number
          required: True

        - name: T
          in: query
          description: Ship draught [m]
          type: number
          required: True

        - name: BK_L
          in: query
          description: Bilge keel length [m]
          type: number
          required: True

        - name: BK_B
          in: query
          description: Bilge keel height [m]
          type: number
          required: True

        - name: OG
          in: query
          description: distance from the still water level O to the roll axis G [m]
          type: number
          required: True

        - name: omega0_hat
          in: query
          description: Nondimensional frequency of motion (OMEGAHAT = OMEGA * SQRT(BRTH / 2 / 9.81))
          type: number
          required: True

        - name: C_b
          in: query
          description: Block coefficient [-]
          type: number
          required: True

        - name: A_0
          in: query
          description: Middship coefficient (A_m/(B*d) [-]
          type: number
          required: True

        - name: V
          in: query
          description: ship speed [m/s]
          type: number
          required: True

        - name: phi_a
          in: query
          description: Roll amplitude [rad]
          type: number
          required: True

      responses:
        200:
          description: Successfully predicted the rolldamping for this ship.
          schema:
            properties:
              lpp:
                type: number
    post:
      operationId: roll_damping.precict_many
      summary: Predict the roll damping of many ships, based on their main dimensions.
      consumes:
        - application/json
      parameters:
        - in: body
          name: ship
          description: The user to create.
          schema:
            $ref: '#/definitions/Ship'
      responses:
        200:
          description: Successfully predicted the rolldamping for this ship.
          schema:
            properties:
              lpp:
                type: number

definitions:
  Ship:           # <----------
    type: object
    required:
      - lpp
    properties:
      lpp:
        description: Ship perpendicular length [m]
        type: number
      beam:
        description: Ship beam [m]
        type: number
      T:
        description: Ship draught [m]
        type: number
      BK_L:
        description: Bilge keel length [m]
        type: number
      BK_B:
        description: Bilge keel height [m]
        type: number
      OG:
        description: distance from the still water level O to the roll axis G [m]
        type: number
      omega0_hat:
        description: Nondimensional frequency of motion (OMEGAHAT = OMEGA * SQRT(BRTH / 2 / 9.81))
        type: number
      C_b:
        description: Block coefficient [-]
        type: number
      A_0:
        description: Middship coefficient (A_m/(B*d) [-]
        type: number
      V:
        description: ship speed [m/s]
        type: number
      phi_a:
        description: Roll amplitude [rad]
        type: number

