swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /roll_damping:
    get:
      operationId: roll_damping.predict
      tags:
        - roll_damping
      summary: Read one person from the roll_damping list
      description: Read one person from the roll_damping list
      parameters:
        - name: lpp
          in: query
          description: Ship perpendicular length [m]
          type: number
          required: True
      responses:
        200:
          description: Successfully read person from roll_damping list operation
          schema:
            properties:
              lpp:
                type: number

